import webbrowser
import pyautogui as p
from time import sleep
import pymsgbox

nome = pymsgbox.prompt('Qual o seu nome?',title='Formulário para preenchimento')
webbrowser.open('https://cursoautomacao.netlify.app/')
sleep(3)
p.hotkey(['ctrl','f'])
p.write('alerta')
p.press('enter')
p.press('enter')
p.press('esc')
p.press('esc')
digiteSeuNome = p.locateCenterOnScreen('Digiteseunome.jpg')
p.click(digiteSeuNome)
p.write(nome)
p.press('tab')
sleep(1.5)
p.press('enter')
sleep(1.5)
p.press('enter')
p.press('pgup')
sleep(1.5)
p.press('pgdn')
p.scroll(-500)
downloadExcel = p.locateCenterOnScreen('download_excel.jpg')
p.click(downloadExcel,duration=0.3)
sleep(2)
p.press('tab')
p.press('tab')
p.press('tab')
p.press('tab')
sleep(1.5)
p.press('enter')
pymsgbox.alert('Tarefa concluída!',title='AUTOMAÇÃO')